### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by licaon-kter** [themighty1/lpfw#37]
@themighty1 Is this dead? In stasis? Abandoned?

**Comment by themighty1** [comment]
Ive been working on the develop branch, adding a testsuite. However due to severe lack of time, I dont foresee any updates from me in the next 6 months or so.

**Comment by magistryo** [comment]
Hi can you please pack lpfw to the deb file for linux mint.
I install this app - but it not running - lpfw closing after start, and gui - not display any data.
Or put it in linux mint repository.

if run gui app under console it show errors - 
""sni-qt/4935" WARN  21:00:26.266 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/usrname/path/lpfw-master/gui/gui.py", line 368, in communicationThread
    with open('/tmp/lpfwcommport', 'r') as f: commport = f.read()
IOError: [Errno 2] No such file or directory: '/tmp/lpfwcommport'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/usrname/path/lpfw-master/gui/gui.py", line 351, in conntrackThread
    with open('/tmp/lpfwctport', 'r') as f: ctport = f.read()
IOError: [Errno 2] No such file or directory: '/tmp/lpfwctport'"

Thanks.

**Comment by magistryo** [comment]
Hi again - please read this post.
I run this app, but in not work properly - https://forums.linuxmint.com/viewtopic.php?f=47&t=241307&p=1294055#p1294055
